name: "ESLint analysis"

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Run npm install
      run: npm install
    - name: Run ESLint
      run: node_modules/.bin/eslint build docs lib script spec-main -f node_modules/@microsoft/eslint-formatter-sarif/sarif.js -o results.sarif || true # eslint exits 1 if it found anything to report :facepalm:
    - uses: Anthophila/codeql-action/codeql/upload-sarif@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        sarif_file: results.sarif
